### ISSUE TITLE
Proposal for this repo

### ISSUE THREAD

**Issue by yuqingc** [dreamtian/library-react#5]
**这个作为大型开源项目，然后稍微提一下建议**

- @dreamtian 自己尽量不要直接往 master push。可以创建分支，然后也发 pr
这个看起来有点乱 ref: https://github.com/dreamtian/library-react/network
![image](https://user-images.githubusercontent.com/29723652/41095971-b4fb9a62-6a85-11e8-9ce0-35af8c7ec265.png)

- 分支管理参考[A successful Git branching model](https://nvie.com/posts/a-successful-git-branching-model/)

- 发pr之前尽量使用 `git rebase` 而不是 `merge` (`git pull`)
ref: https://github.com/dreamtian/library-react/pull/4
ref: https://github.com/dreamtian/library-react/pull/3

- 在适当的时候发布 release 版本

- 增加一些功能 比如 pr issue 的模板
ref: https://github.com/dreamtian/library-react/community

- 添加 License
[MIT](https://github.com/dreamtian/library-react/community/license/new?branch=master&template=mit) or [Apache 2.0](https://github.com/dreamtian/library-react/community/license/new?branch=master&template=apache-2.0) ?

- 把小伙伴们加入 [Collaboration](https://github.com/dreamtian/library-react/settings/collaboration)

**Comment by yuqingc** [comment]
@dreamtian @sosohime

**Comment by dreamtian** [comment]
really appreciate the suggestions
